name: Main

on:
  push:
    branches:
      - helium
  pull_request:
    branches:
      - helium

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            python3-pip \
            shellcheck \
            cppcheck
      - name: Install 'black'
        run: python3 -m pip install "black==19.3b0"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for do-lint
      - name: Run lint
        run: ./tools/circle-ci/do-lint

  build:
    runs-on: ubuntu-latest     
    env:
      MACHINE: ${{ matrix.machine }}
      CACHE_DIR: /tmp/job/sstate-cache
      CACHE_URI: https://fb-openbmc-sstate.s3.us-east-2.amazonaws.com
    strategy:
      matrix:
        machine:
          [
            angelslanding,
            # cmm,
            # elbert,
            # emeraldpools,
            # clearcreek,
            # cloudripper,
            # fbgp2,
            # fbtp,
            # fbttn,
            # fby2,
            # fby3,
            # fuji,
            # galaxy100,
            # grandcanyon,
            # lightning,
            # minipack,
            # northdome,
            # sonorapass,
            # wedge,
            # wedge100,
            # wedge400,
            # yamp,
            # yosemite,
          ]
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
            build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
            xz-utils debianutils iputils-ping
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for check-build-required
      - name: Sync Yocto Repository
        run: ./sync_yocto.sh  # GitHub Action's upload artifact complains about too many files.
      - name: Check build required
        run: ./tools/circle-ci/check-build-required
      # - name: Download sstate cache
      #   run: ./tools/circle-ci/download-sstate-cache
      - name: Build
        run: ./tools/circle-ci/do-build
